### ISSUE TITLE
Fix Jury UX category sorts and comment/flag associations and/or rendering

### ISSUE THREAD

**Issue by lahollen** [therabble/seattle-public-library-client#43] opened 2016-04-29 21:10 UTC
When selecting recommend for the album Hee Haw by Kelly from YourQueue, the album does not move to the Recommended tab or out of YourQueue. I am prompted to comment and the note added to the album that says it has been "recommended by undefined." The album also does not appear in the invite interface.

Signed into juror interface as admin user Kreg Hasegawa. Mac, Firefox, 4/29, 4:00PM CT.

**Comment by mbrakken** [comment] 2016-04-29 21:31
Not removing stuff from "Your Queue" was intended. It's a different thing
than the other queues, since other people's actions on an item should not
remove stuff from one's queue.

Going into the "Recommended" tab is a separate consideration. It it's not
in there, it's likely a bug in the template updating. I just tested adding
something from the Pending queue and it did move.

If people want stuff to move from Your Queue, that'll require formally
removing it when the juror takes an action on it.

Undefined name is likely a simple bug. something isn't being set in the
proper order.

**Comment by lahollen** [comment] 2016-04-29 21:49
Thanks for the clarification. Ignore my comments on moving stuff out of "Your Queue."

Update: When logged in as admin user Andrew Harbison, I am able to recommend the album Pacifica Poets from "Your Queue" and it appears in the Recommended tab. So it seems to work fine for that user.

But I retested logged in as Kreg and had a similar issue. I recommended album Test Kreg from "Your Queue" but it did not appear in the Recommended tab or Invite interface.

Mac, Firefox, 4/29, 4:45pm CT.

**Comment by prestonaustin** [comment] 2016-05-10 20:24
@lahollen @mbrakken Changing title here from "Recommended album in YourQueue not moving to Recommended" to "Fix Jury UX category sorts and comment/flag associations and/or rendering"

**Comment by prestonaustin** [comment] 2016-05-10 20:27
@mbrakken Please work on this on a "jury_fixes_wip[whatever]" branches. Assign any remaining wip back to me Friday AM so I can look it over and get your input on Friday, as I hope to deliver before Monday AM.

**Comment by kellyhiser** [comment] 2016-05-19 15:04
@mbrakken deployed fix last night - #65 - but my flags aren't saving. Closing this issue as requested, opening new bug report #66

**Closed by kellyhiser** 2016-05-19 15:04 UTC
Labels: bug, SPL blocker
